language: cpp
sudo: false

addons:
  apt:
    packages:
      - libc6-i386
  coverity_scan:
    project:
      name: "amq/tiva_oled_joystick"
      description: "Build submitted via Travis CI"
    notification_email: "amq@users.noreply.github.com"
    build_command_prepend: "make clean; cov-configure --compiler arm-none-eabi-gcc --comptype gcc --template"
    build_command: "make"
    branch_pattern: coverity_scan
    secure: "mN4TiSSxv5NwpZhw0q4MBCEK3KEwlx6yHLNU9Gnn4e3hQZcnDWtOAYmHW4dI6cqfi28obFWeXWMXaL7ykrEU+X++OX73FmfQI6zrrTBJ23pOQUUGWxXf9EZMOJe+2SzKrUQIiB0B4Ya60Fj1HB2q5RNC+gE9ci5TqK5E6dPtEjEKvTihxapp5l2bj86GTax4SPwca5UV3LnxDzj/Df47HVEzLFNm8JUPTVtvDQX5GDaVSWMaP+01WZ0GF2LRr+r6PPdSNpRXqNHU2HBcjtq34QgPV4UAIuw45RwB18pbKn//PWA58X9Nlakf2ueYiXPJhQ5dTv19eijOx5tHCxiUJN8YARRfeb61Pu+SDkf4NHNZeqHIws/TxPENGSHOzoIz61dmHKAllEUh1KOb4tJhd//F+oZBuwrJyjLDQOavbquELpJRgJUAxz16RzME19qgGQwEDyDEVvZIQ8/A0kruhmjG8Iir55btqmfeGMf07BiJrvig5Kel8jvGX5XAA9G8CrPldj4cF6sQGgk+V2vn3s+g3K/9QZaYpjYWETARiiYvXjS1U56xNdhIlEbRSx8Fo0W11QigQRiNKQrlGTEa9KQlsapF8PfF4bKRfhWlSbeLQYoIrbYvI9aKFGxTD01p7FMuUrrhvHvAh5wlLrD3wQupcUYd1pc1OJCY284TQ3I="

env:
  global:
    - GCC_DIR="$HOME/gcc-arm-none-eabi-6_2-2016q4"
    - GCC_URL="https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2016q4/gcc-arm-none-eabi-6_2-2016q4-20161216-linux.tar.bz2"
    - XDCTOOLS_DIR="$HOME/ti/xdctools_3_32_00_06_core"
    - TIRTOS_DIR="$HOME/ti/tirtos_tivac_2_16_01_14"
    - TIRTOS_URL="http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/tirtos/2_16_01_14/exports/tirtos_tivac_setuplinux_2_16_01_14.bin"

cache:
  directories:
    - $GCC_DIR
    - $XDCTOOLS_DIR
    - $TIRTOS_DIR

install:
  - if [ ! -e $XDCTOOLS_DIR/xs ]; then wget $TIRTOS_URL -O tirtos.bin; chmod +x tirtos.bin; ./tirtos.bin --mode unattended; fi
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-gcc ]; then wget $GCC_URL -O gcc.tar.bz2; tar xfj gcc.tar.bz2 -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin

script:
  - make -j 2

deploy:
  provider: releases
  api_key:
    secure: TdugPJfpq3WcDV6UykIh5GPfB6gFOTMf4NNaee3/VpcdiiO9O2Yrrtw41UcRN6FtvMVB1cxj3A5EzDF3NwzfSC+LZTYU8aVJgUVh3Le8RgMnK4Vy+OYAjTN39ve4+Z2zkmELapmvROjhjnZl7X1MiPn7iiP209VSaNxFR6z5KDz6TmacoE8uqRGXSotE6sPVMEROIT9WKRj5H9/04aMcVDay+wK9Jwqw9ZloFvQPC2DaCxZ+424vFrBCEuBamqlQyxp6t9DiU/OpUD6SabAdEvirf69hR9o4mBf7y2R6iS2Wnh85pgJgDEdhs2NjfGtAoOqXPp6OQkR5E+rAdw0Tn8RR0jQ3s5dgff2blngDv7jC5ScXjc8VQN5V2r8Wy6g+lZWUh9xwE8G5ZOUFgvIn6TEcplFb6yGknIzdTcVT7DlYKvzMj/ZeiSIH9lzZOdxQY8Sn/kvxhSQLx+QLVDn+1p0hPkSrHzDWL4jcALBzxHxYJY8v2wBuBTKTJD2bPw5sdkD5bFAxTL92IRvIU/GWvyAmANR4/Q0erIvKe9jMpiJ+VSoYaajR/k+EuVLFdmNpWFFqiSMLA0Zyh2Dejcfk6rVwqVGv4qyyPn+MMc4Qa+pdsaPJdsqqM7BMkStzzGZEUQGYdBv88r2HrLQ0VN/dk8wIv7SEgJ4Lr6mSH8QUGzg=
  file: tiva_oled_joystick.out
  skip_cleanup: true
  on:
    tags: true
